### ISSUE TITLE
add class to <table> in ng2-table

### ISSUE THREAD

**Issue by bmsdave** [valor-software/ng2-table#170]
Hello

How can I pass the class <table> in the component.
I want to hang their styles through the class .
whether it is possible to implement it in the current version ?

**Comment by cioraneanu** [comment]
Also interested in this! :)

**Comment by felimartina** [comment]
Also interested!
No way to change the default classes passed to the `<table>` rendered?
This are the classes I am getting: `table table-striped table-bordered dataTable` I'd like to remove the striping and add some of my own classes.

**Comment by masiamj** [comment]
Also interested in this! Great component- any update on dynamic styling?

**Comment by grachevko** [comment]
+1

**Comment by michaeljohnbennett** [comment]
I'm in the same boat, I also saw on the main datatable site there are options to style or create your own custom stylesheets.

I'm really needing to make some compact tables but again stumped like the rest.

Any advice would be appreciated.

**[https://datatables.net/manual/styling/bootstrap]()**

I would imagine adding an input and passing it on might work but I'm sure there should a more elegant way to do this. 

I'm currently working with rc6 and have it inside a module and everything else is working fine.

Excellent functionality, adding styling support would make it immense! :+1:
