### ISSUE TITLE
No value accessor for ''

### ISSUE THREAD

**Issue by Perezmarc** [valor-software/ng2-table#188]
Hi, I installed it by npm but keep getting this error. 

I modified a little bit my project since I am using angular2-seed skafolding. The HTML looks the same as the example:
`import {Component, OnInit} from '@angular/core';
import {CORE_DIRECTIVES, FORM_DIRECTIVES, NgClass, NgIf} from '@angular/common';
import {PAGINATION_DIRECTIVES} from 'ng2-bootstrap/ng2-bootstrap';
import {NG_TABLE_DIRECTIVES} from 'ng2-table/ng2-table';
import {TableData} from './table-data';

@Component({
    moduleId: module.id,
  selector: 'table-demo',
  templateUrl: 'table-section.component.html',
  directives: [NG_TABLE_DIRECTIVES, PAGINATION_DIRECTIVES, NgClass, NgIf, CORE_DIRECTIVES, FORM_DIRECTIVES]
})
export class TableDemoComponent implements OnInit {
  public rows:Array<any> = [];
  public columns:Array<any> = [
    {title: 'Name', name: 'name'},
    {title: 'Position', name: 'position', sort: false},
    {title: 'Office', name: 'office', sort: 'asc'},
    {title: 'Extn.', name: 'ext', sort: ''},
    {title: 'Start date', name: 'startDate'},
    {title: 'Salary ($)', name: 'salary'}
  ];
  public page:number = 1;
  public itemsPerPage:number = 10;
  public maxSize:number = 5;
  public numPages:number = 1;
  public length:number = 0;

  public config:any = {
    paging: true,
    sorting: {columns: this.columns},
    filtering: {filterString: '', columnName: 'position'}
  };

  private data:Array<any> = TableData;

  public constructor() {
    this.length = this.data.length;
  }

  public ngOnInit():void {
    this.onChangeTable(this.config);
  }

  public changePage(page:any, data:Array<any> = this.data):Array<any> {
    console.log(page);
    let start = (page.page - 1) \* page.itemsPerPage;
    let end = page.itemsPerPage > -1 ? (start + page.itemsPerPage) : data.length;
    return data.slice(start, end);
  }

  public changeSort(data:any, config:any):any {
    if (!config.sorting) {
      return data;
    }

```
let columns = this.config.sorting.columns || [];
let columnName:string = void 0;
let sort:string = void 0;

for (let i = 0; i < columns.length; i++) {
  if (columns[i].sort !== '') {
    columnName = columns[i].name;
    sort = columns[i].sort;
  }
}

if (!columnName) {
  return data;
}

// simple sorting
return data.sort((previous:any, current:any) => {
  if (previous[columnName] > current[columnName]) {
    return sort === 'desc' ? -1 : 1;
  } else if (previous[columnName] < current[columnName]) {
    return sort === 'asc' ? -1 : 1;
  }
  return 0;
});
```

  }

  public changeFilter(data:any, config:any):any {
    if (!config.filtering) {
      return data;
    }

```
let filteredData:Array<any> = data.filter((item:any) =>
  item[config.filtering.columnName].match(this.config.filtering.filterString));

return filteredData;
```

  }

  public onChangeTable(config:any, page:any = {page: this.page, itemsPerPage: this.itemsPerPage}):any {
    if (config.filtering) {
      Object.assign(this.config.filtering, config.filtering);
    }
    if (config.sorting) {
      Object.assign(this.config.sorting, config.sorting);
    }

```
let filteredData = this.changeFilter(this.data, this.config);
let sortedData = this.changeSort(filteredData, this.config);
this.rows = page && config.paging ? this.changePage(page, sortedData) : sortedData;
this.length = sortedData.length;
```

  }
}
`

**Comment by maracinebogdan88** [comment]
Same Pb here ... does anyone have a solution  ?

**Comment by alaa-bourouissi** [comment]
Any solution ???

**Comment by valorkin** [comment]
use new forms
`import {CORE_DIRECTIVES, FORM_DIRECTIVES, NgClass, NgIf} from '@angular/common';`
this is deprecated forms

**Comment by whileLooper** [comment]
I have same problem with you, my angular2 rc4
I think I'm using the latest form from angular2
@Perezmarc do you solve the problem at the end?

**Comment by reach4thelasers** [comment]
I've been battling with this issue for 3 hours.  The Solution is to forcably disable legacy forms in the bootstrap call in main.ts:

```

return bootstrap(App, [
     disableDeprecatedForms(),
     provideForms(),
....
```

and then to import the new ones in place of the old ones (the old ones were in @angular/common)

```
`import {FORM_DIRECTIVES} from '@angular/forms/src/directives';`
```

also make sure you have angular forms 0.2.0 in your packages.json

**Comment by whileLooper** [comment]
@reach4thelasers @valorkin 
I have check all my setting, latest version ng2-bootstrap 1.0.24, angular forms 0.2.0, angular2 rc4, correct `import {FORM_DIRECTIVES} from '@angular/forms/src/directives'; ` and `disableDeprecatedForms(),  provideForms(),` in `main.ts` 
I still have errors `No provider for NgModel ` 
can you help me, check if I miss anything above?

**Comment by whileLooper** [comment]
oh, I just found out, I posted in the wrong section,
My problem is in the ng2-bootstrap pagination, ng2-table works fine for me now
@reach4thelasers thx your help anyway
