### ISSUE TITLE
Add Row 

### ISSUE THREAD

**Issue by lkc513** [valor-software/ng2-table#239]
Hi all expert,

Any idea can advice me how to add a "Add New Row" function into this ng2-table ?

Appreciate if anyone of you can advice me... 

thank you...

**Comment by eolcum** [comment]
You should add the row data to the bound component variable. The table would be automatically updated.

**Comment by lkc513** [comment]
Yes, i do on this way.

HTML
`<div id="button-div-header-sub-crud" *ngIf="action != 'view'">
<button type="button" class="btn btn-default btn-sm" (click)="mf3.add(newStudents())">{{label.button.add}}
</button>   
</div>`

TypeScript
`private newStudents() {
        return new Students()
    }`
