### ISSUE TITLE
Reg: ng2-table:1 Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by prashantverma123** [valor-software/ng2-table#27]
Hi i am getting an error for unexpected token while using ng2 table package.
I even mapped the ng2 table in my index.html

**Comment by lnevaril** [comment]
Unexpected token '<' means that it is expecting javascript but it reads html, check in console that you are correctly loading ng2-table modules files (at first I had the same problem)

**Comment by valorkin** [comment]
@lnevaril thx for helping :)

**Comment by prashantverma123** [comment]
Thanks for the help
