### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by zagreusinoz** [valor-software/ng2-table#275]
Hi there, just letting you know that your demo isn't working at the moment.  I got the following console error:

Failed to load resource: the server responded with a status of 404 (Not Found)
zone.js:484Unhandled Promise rejection: Failed to load demo/components/table-section.html ; Zone: <root> ; Task: Promise.then ; Value: Failed to load demo/components/table-section.html undefinedconsoleError @ zone.js:484
zone.js:486Error: Uncaught (in promise): Failed to load demo/components/table-section.html(…)consoleError @ zone.js:486

**Comment by gtvforever** [comment]
Here is the console log from Chrome:

http://valor-software.com/ng2-table/demo/components/table-section.html Failed to load resource: the server responded with a status of 404 (Not Found)
zone.js:484Unhandled Promise rejection: Failed to load demo/components/table-section.html ; Zone: <root> ; Task: Promise.then ; Value: Failed to load demo/components/table-section.html undefinedconsoleError @ zone.js:484
zone.js:486Error: Uncaught (in promise): Failed to load demo/components/table-section.html(…)

**Comment by goden** [comment]
Demo page always display "loading"...

**Comment by bernardogontijo** [comment]
+1

**Comment by tscislo** [comment]
+1

**Comment by TeodorKolev** [comment]
+1

**Comment by michabbb** [comment]
@bernardogontijo @tscislo @TeodorKolev you know that this is for ??

![schnappschuss_092816_054449_pm](https://cloud.githubusercontent.com/assets/3524595/18920939/413db254-85a3-11e6-9898-1e98a988e18d.jpg)

**Comment by DanielMcAssey** [comment]
+1

**Comment by valorkin** [comment]
Yep, upgrading to latest ng2 and will be deployed

**Comment by DaveStoneDotNet** [comment]
+1

**Comment by valorkin** [comment]
http://valor-software.com/ng2-table/ fixed
published with AoT compliance
