### ISSUE TITLE
Demo not working / need setup help

### ISSUE THREAD

**Issue by Faigjaz** [valor-software/ng2-table#290]
I'm trying to get ng2-tables to work, but the Usage/Docs section is not available. 
As I am a newbe, I'm not quite sure what to do. 
I using the latest Angular2 version.

I installed ng2-table via npm and am trying to import to my component like so: 

import { NgTableComponent, NgTableFilteringDirective, NgTablePagingDirective, NgTableSortingDirective } from 'ng2-table/ng2-table';

within my @ NgModule I have 

@ NgModule({
   imports: [
      Ng2TableModule
   ],

I am inserting the script 

'./node_modules/ng2-table/bundles/ng2-table.min.js' 

into my html. 

But I am getting this error:

```
Can't bind to 'rows' since it isn't a known property of 'ngTable'. ("

</div>-->
<ngTable [ERROR ->][rows]="devices" [columns]="columns">
      </ngTable>

"): DeviceOverviewComponent@17:9
Can't bind to 'columns' since it isn't a known property of 'ngTable'. ("

</div>-->
<ngTable [rows]="devices" [ERROR ->][columns]="columns">
      </ngTable>

"): DeviceOverviewComponent@17:26
'ngTable' is not a known element:
1. If 'ngTable' is an Angular component, then verify that it is part of this module.
2. If 'ngTable' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. ("

</div>-->
[ERROR ->]<ngTable [rows]="devices" [columns]="columns">
      </ngTable>

```

**Comment by alexzuza** [comment]
I guess it should be 
`<ng-table [rows]="devices" [columns]="columns"></ng-table>`

**Comment by Faigjaz** [comment]
The ordere doesn't seem to be of interest. 
I needed to add

```
import {CUSTOM_ELEMENTS_SCHEMA} from '@angular/core'

@NgModule({
 ...,
schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
within my app.module.ts. Got this from the docs of another npm-package...
```

Here's my SO question with more code in it, so people with same problem might be helped.

[http://stackoverflow.com/questions/39608919/ng2-table-not-working-with-latest-angular2-version/39609820#39609820](url)

**Comment by alexzuza** [comment]
@Faigjaz You shouldn't use `CUSTOM_ELEMENTS_SCHEMA`

**Comment by scorbin** [comment]
i give up

**Comment by Faigjaz** [comment]
@scorbin 

My mistake actually was that  I used the wrong selector in here. I used `<ngTable> </ngTable> ` where it should've been `<ng-table></ng-table>`. Also you need to add the ng2TableModule to your app.module.ts inside the "Imports"-Array. And don't Forget to add the css/js into your index.html (if needed, I'm not quite sure, I don't use this anymore). Hope I could help.

**Comment by webrexRavi** [comment]
need to import in your common module **app.module.ts**
it works for me
