### ISSUE TITLE
How to limit the height of the scrollable area?

### ISSUE THREAD

**Issue by danny-swimmer** [valor-software/ng2-table#374]
I am setting itemsPerPage=1000.
The ng2-table works very well - it displays all 1000 items.
However I would like to limit the height of the scrollable area, so that only 20 rows are shown at one time. How can I do this?
I've tried setting the css 'height' attribute on the ng2-table, or on an enclosing 'div' tag, but this does not work.

**Comment by eBitzu** [comment]
You can add a class on witch you set the CSS for the table.. like height: 300px and overflow-y: auto

**Comment by danny-swimmer** [comment]
Thanks @eBitzu. This works well. I'm closing the ticket.
