### ISSUE TITLE
How to adjust the size of column?

### ISSUE THREAD

**Issue by kumar-pranjal** [valor-software/ng2-table#381]
I need to display 15 columns in the table, but 6 columns are visible on the screen, other columns are being generated in HTML but are not visible as the width of visible columns is too high.

Any help for reducing the column width or assign auto width to column would be helpful.

**Comment by hackathon365** [comment]
I think you can do with column's class-name.

**Comment by kumar-pranjal** [comment]
I had to update the ng-table.component.js

**Comment by ibrahim978976** [comment]
Yes.i need to resize a column in ng2-table.what i need to do?
