### ISSUE TITLE
Sort Priority

### ISSUE THREAD

**Issue by webcat12345** [valor-software/ng2-table#386]
There are 2 columns on my table **name** and **description**.
When loading, I want to sort table by **name** column. also **description** column should contains sort feature.

so I used : `Name : sort : 'asc'` and `Description : sort : true`.
But it does not sorted by name column.

I tried to set `Description : sort : false` and `Name : sort : 'asc'`. It works well.
But in this case **Description** column has no sort feature.

How can I solve this?

**Comment by webcat12345** [comment]
I solved this issue myself.
**Get initial loading event with new parameter.**
 
`this.onChangeTable(this.config, false);`

**2th parameter** is the value for getting **initial loading**.

`
public onChangeTable(config:any, initial_flag:any, page:any = {page: this.page, itemsPerPage: this.itemsPerPage}):any {
    if (config.filtering) {
      Object.assign(this.config.filtering, config.filtering);
    }

    if (config.sorting) {
      Object.assign(this.config.sorting, config.sorting);
    }

    let filteredData = this.changeFilter(this.data, this.config);
    let sortedData = this.changeSort(filteredData, this.config, initial_flag);
    this.rows = page && config.paging ? this.changePage(page, sortedData) : sortedData;
    this.length = sortedData.length;
    this.ref.detectChanges();
  }
`

Get initial loading parameter and send it to **Change Sort** function.
**Change Sort function** gets initial parameter and doing sort with only name table.

`
  public changeSort(data:any, config:any, initial_flag:any):any {
    if (!config.sorting) {
      return data;
    }

    let columns = this.config.sorting.columns || [];
    let columnName:string = void 0;
    let sort:string = void 0;

    if (initial_flag) {
      columnName = 'name';
      sort = 'asc';
    } else {
      for (let i = 0; i < columns.length; i++) {
        if (columns[i].sort !== '' && columns[i].sort !== false) {
          columnName = columns[i].name;
          sort = columns[i].sort;
        }
      }
    }

      if (!columnName) {
        return data;
    }
`

**Comment by priyakokas** [comment]
this works but according to the pagination. once pagination is changed it breaks.

**Comment by priyakokas** [comment]
Great Job (Y)

**Comment by priyakokas** [comment]
it doesnt work on pagination. plus other filters doesnt work
