### ISSUE TITLE
Errro: Can't bind to ngTableFiltering

### ISSUE THREAD

**Issue by lcborn4** [valor-software/ng2-table#407]
Error: Can't bind to 'ngTableFiltering' since it isn't a known property of 'input'.

I have only implemented this part

<div>
     <input *ngIf="config.filtering" placeholder="Filter all columns"
     [ngTableFiltering]="config.filtering"
     class="form-control"
     (tableChanged)="onChangeTable(config)"/>
</div>

**Comment by lcborn4** [comment]
derp NgModule

**Comment by SinaArdehali** [comment]
excuse me, i am not english and i did not understand . what "derp NgModule" mean?

**Comment by Zar-rok** [comment]
I had this error because I only add `import { Ng2TableModule } from 'ng2-table/ng2-table';` in `app.module.ts` and it's seems to not be enough. So I add `Ng2TableModule` to the import list of the `@NgModule` block and it have fix : 
> Error: Can't bind to 'ngTableFiltering' since it isn't a known property of 'input'.
