### ISSUE TITLE
how to get data from json rather from table-data.ts

### ISSUE THREAD

**Issue by new2angular2** [valor-software/ng2-table#418]
how can i achieve that.iam new to angular2.anyone please help me out its urgent

``

**Comment by brocktubre** [comment]
So in your component or service (when you are retrieving data you want to add to the ng2 table), you can create a temporary object or variable that has attributes that match specifically the columns in your table. 

For instance I created a variable called `obj` with the data I wanted to be a part of a row. Then pushed `obj` onto the tables `this.data` array.

```
let obj = {
        name: item.name,
        type: item.type,
        serialNumber: item.serialNumber,
        amount: item.amount
};
this.data.push(obj);
```

You also want to make sure the `name` attribute when declaring your columns is **the same** as your attributes on the object you are pushing onto the `this.data` array.

```
public columns:Array<any> = [
    {title: 'Name', name: 'name', sort: 'asc'},
    {title: 'Type', name: 'type', sort: 'asc'},
    {title: 'Serial Number', name: 'serialNumber', sort: 'asc'},
    {title: 'Amount', name: 'amount'}
  ];
```

**Comment by new2angular2** [comment]
@brocktubre 

Table-component.ts


  public rows:Array<any> = [];
  public columns:Array<any> = [
    {title: 'Company', name: 'name', filtering: {filterString: '', placeholder: 'Filter by Company'}},
    {
      title: 'Position',
      name: 'position',
      sort: false,
      filtering: {filterString: '', placeholder: 'Filter by Position'}
    },

    {title: 'Location', name: 'office', sort: '', filtering: {filterString: '', placeholder: 'Filter by Location'}},
    {title: 'Date', className: 'text-warning', name: 'startDate'},
  
  ];
  public page:number = 1;
  public itemsPerPage:number = 10;
  public maxSize:number = 5;
  public numPages:number = 1;
  public length:number = 0;

  public config:any = {
    paging: true,
    sorting: {columns: this.columns},
    filtering: {filterString: ''},
    className: ['table-striped', 'table-bordered']
  };

  private data:Array<any> = TableData;


Tabledata.ts

 {
    'name': 'Victoria Cantrell',
    'position': 'Integer Corporation',
    'office': 'Croatia',
    'ext': `<strong>0839</strong>`,
    'startDate': '2015/08/19',
    'salary': 208.178
  }, {
    'name': 'Pearl Crosby',
    'position': 'In PC',
    'office': 'Cambodia',
    'ext': `<strong>8262</strong>`,
    'startDate': '2014/10/08',
    'salary': 114.367
  }, {
    'name': 'Colette Foley',
    'position': 'Lorem Inc.',
    'office': 'Korea, North',
    'ext': '8968',
    'startDate': '2015/07/19',
    'salary': 721.473
  }, {
    'name': 'Anastasia Shaffer',
    'position': 'Dolor Nulla Semper LLC',
    'office': 'Suriname',
    'ext': '7980',
    'startDate': '2015/04/20',
    'salary': 264.620
  }, {
    'name': 'Gabriel Castro',
    'position': 'Sed Limited',
    'office': 'Bahrain',
    'ext': '0757',
    'startDate': '2015/03/04',
    'salary': 651.350
  }, {
    'name': 'Cherokee Ware',
    'position': 'Tincidunt LLC',
    'office': 'United Kingdom (Great Britain)',
    'ext': '3995',
    'startDate': '2015/06/17',
    'salary': 666.259
  }, {
    'name': 'Barry Moss',
    'position': 'Sociis Industries',
    'office': 'Western Sahara',
    'ext': '6697',
    'startDate': '2015/08/13',
    'salary': 541.631
  }
]

I know that   private data:Array<any> = TableData; in component code getting data from table-data.ts

but I want to get data for the table from an external JSON using HTTP GET rather than from table.ts

**Comment by brocktubre** [comment]
@new2angular2 

So in your component (or service if you decide to create one) you can make the HTTP GET request and map that JSON data into the `data` array that ng2-table provides. You can add this logic in the `ngOnit()` method which will be called when the component is loaded. See comments in below code.

```
public rows:Array = [];
public columns:Array = [
  {title: 'Company', name: 'name', filtering: {filterString: '', placeholder: 'Filter by Company'}},
  {title: 'Position', name: 'position', sort: false, filtering: {filterString: '', placeholder: 'Filter by Position'}},
  {title: 'Location', name: 'office', sort: '', filtering: {filterString: '', placeholder: 'Filter by Location'}},
  {title: 'Date', className: 'text-warning', name: 'startDate'},
];

public page:number = 1;
public itemsPerPage:number = 10;
public maxSize:number = 5;
public numPages:number = 1;
public length:number = 0;

public config:any = {
  paging: true,
  sorting: {columns: this.columns},
  filtering: {filterString: ''},
  className: ['table-striped', 'table-bordered']
};


// Make your table into a generic array.
private data:Array = []; 

constructor(private http: HttpService) { }

/*
* When the component is loaded, we want to fill this.data array with
*  the JSON data we are retrieving with the HTTP GET request.
*/
ngOnit(){
     this.getJsonData().subscribe(itemsFromGetRequest =>{
         /* Loop through the items for the HTTP GET request and insert them into the data array (the table). */
         itemsFromGetRequest.forEach(item => {
             this.data.push(item);
         });
     });
}

public getJsonData(): Observable<any[]>{
  /* Change this to the URL of the API you are requesting the data from. */
  let uri = 'http://your-api-call.com/location/to/http/request.json';
  return this.http.get(uri)
        .map((response: Response) => {
            let items = response.json(); /* Here is where the table is filled with data. */
            return items;
    }).catch((error:any) => Observable.throw(error.json().error || 'Error retrieving the data.'));
}
```

**Comment by new2angular2** [comment]
@brocktubre  Thank you so much for replies.

But angular didn't throw any error, data is not loading from rest. Table is empty.Can you please rectify my code.whether I need to do some imports or anything I'm doing wrong in retrieving the data..Thanks

**REST** : [https://s3.ap-south-1.amazonaws.com/jsonlink/table-data.json](url)

[
  {
    "name": "Victoria Cantrell",
    "position":"Integer Corporation",
    "office": "Croatia",
    "ext": "0839",
    "startDate": "2015/08/19",
    "salary": 208.178
  },
  {
    "name": "Victoria Cantrell",
    "position":"Integer Corporation",
    "office": "Croatia",
    "ext": "0839",
    "startDate": "2015/08/19",
    "salary": 208.178
  },
  {
    "name": "Victoria Cantrell",
    "position":"Integer Corporation",
    "office": "Croatia",
    "ext": "0839",
    "startDate": "2015/08/19",
    "salary": 208.178
  },
  {
    "name": "Victoria Cantrell",
    "position":"Integer Corporation",
    "office": "Croatia",
    "ext": "0839",
    "startDate": "2015/08/19",
    "salary": 208.178
  },
  {
    "name": "Victoria Cantrell",
    "position":"Integer Corporation",
    "office": "Croatia",
    "ext": "0839",
    "startDate": "2015/08/19",
    "salary": 208.178
  }
 ]

**Table-demo.component.ts**

import { Component, OnInit } from '@angular/core';
import {Http, Response,RequestOptions,Headers,BaseRequestOptions} from '@angular/http';
import {Observable} from 'rxjs/Observable';
import {TableData} from '../table-demo/table-data';

@Component({
  selector: 'app-table-demo',
  templateUrl: './table-demo.component.html',
  styleUrls: ['./table-demo.component.css','./prism-okaidia.css','./glyphicons.css']
})
export class TableDemoComponent implements OnInit {

public rows:Array<any> = [];
  public columns:Array<any> = [
    {title: 'Company', name: 'name', filtering: {filterString: '', placeholder: 'Filter by name'}},
    {
      title: 'Position',
      name: 'position',
      sort: false,
      filtering: {filterString: '', placeholder: 'Filter by position'}
    },

    {title: 'Location', name: 'office', sort: '', filtering: {filterString: '', placeholder: 'Filter by Location'}},
    {title: 'Date', className: 'text-warning', name: 'startDate'},
  
  ];
  public page:number = 1;
  public itemsPerPage:number = 10;
  public maxSize:number = 5;
  public numPages:number = 1;
  public length:number = 0;

  public config:any = {
    paging: true,
    sorting: {columns: this.columns},
    filtering: {filterString: ''},
    className: ['table-striped', 'table-bordered']
  };

  private data:Array<any> = [];

 constructor(private http: Http) {this.length = this.data.length;}

/*
* When the component is loaded, we want to fill this.data array with
*  the JSON data we are retrieving with the HTTP GET request.
*/
ngOnit(){
     this.getJsonData().subscribe(itemsFromGetRequest =>{
         /* Loop through the items for the HTTP GET request and insert them into the data array (the table). */
         itemsFromGetRequest.forEach(item => {
             this.data.push(item);
         });
     });
}

public getJsonData(): Observable<any[]>{
  /* Change this to the URL of the API you are requesting the data from. */
  let uri = 'https://s3.ap-south-1.amazonaws.com/jsonlink/table-data.json';
  return this.http.get(uri)
        .map((response: Response) => {
            let items = response.json(); /* Here is where the table is filled with data. */
            return items;
    }).catch((error:any) => Observable.throw(error.json().error || 'Error retrieving the data.'));
}





  public ngOnInit():void {
    this.onChangeTable(this.config);
  }

  public changePage(page:any, data:Array<any> = this.data):Array<any> {
    let start = (page.page - 1) * page.itemsPerPage;
    let end = page.itemsPerPage > -1 ? (start + page.itemsPerPage) : data.length;
    return data.slice(start, end);
  }

  public changeSort(data:any, config:any):any {
    if (!config.sorting) {
      return data;
    }

    let columns = this.config.sorting.columns || [];
    let columnName:string = void 0;
    let sort:string = void 0;

    for (let i = 0; i < columns.length; i++) {
      if (columns[i].sort !== '' && columns[i].sort !== false) {
        columnName = columns[i].name;
        sort = columns[i].sort;
      }
    }

    if (!columnName) {
      return data;
    }

    // simple sorting
    return data.sort((previous:any, current:any) => {
      if (previous[columnName] > current[columnName]) {
        return sort === 'desc' ? -1 : 1;
      } else if (previous[columnName] < current[columnName]) {
        return sort === 'asc' ? -1 : 1;
      }
      return 0;
    });
  }

  public changeFilter(data:any, config:any):any {
    let filteredData:Array<any> = data;
    this.columns.forEach((column:any) => {
      if (column.filtering) {
        filteredData = filteredData.filter((item:any) => {
          return item[column.name].match(column.filtering.filterString);
        });
      }
    });

    if (!config.filtering) {
      return filteredData;
    }

    if (config.filtering.columnName) {
      return filteredData.filter((item:any) =>
        item[config.filtering.columnName].match(this.config.filtering.filterString));
    }

    let tempArray:Array<any> = [];
    filteredData.forEach((item:any) => {
      let flag = false;
      this.columns.forEach((column:any) => {
        if (item[column.name].toString().match(this.config.filtering.filterString)) {
          flag = true;
        }
      });
      if (flag) {
        tempArray.push(item);
      }
    });
    filteredData = tempArray;

    return filteredData;
  }

  public onChangeTable(config:any, page:any = {page: this.page, itemsPerPage: this.itemsPerPage}):any {
    if (config.filtering) {
      Object.assign(this.config.filtering, config.filtering);
    }

    if (config.sorting) {
      Object.assign(this.config.sorting, config.sorting);
    }

    let filteredData = this.changeFilter(this.data, this.config);
    let sortedData = this.changeSort(filteredData, this.config);
    this.rows = page && config.paging ? this.changePage(page, sortedData) : sortedData;
    this.length = sortedData.length;
  }

  public onCellClick(data: any): any {
    console.log(data);
  }
}

**Comment by new2angular2** [comment]
Finally, I got it @brocktubre  Thanks for Replies,

If anyone struggling to get data from API use it.,




# **Table-demo.component.ts**


 import { Component, OnInit } from '@angular/core';
import {Http, Response,RequestOptions,Headers,BaseRequestOptions} from '@angular/http';
import {Observable} from 'rxjs/Observable';
 

@Component({
  selector: 'app-table-demo',
  templateUrl: './table-demo.component.html',
  styleUrls: ['./table-demo.component.css','./prism-okaidia.css','./glyphicons.css']
})
export class TableDemoComponent implements OnInit {

public rows:Array<any> = [];
  public columns:Array<any> = [
    {title: 'Company', name: 'name', filtering: {filterString: '', placeholder: 'Filter by name'}},
    {
      title: 'Position',
      name: 'position',
      sort: false,
      filtering: {filterString: '', placeholder: 'Filter by position'}
    },

    {title: 'Location', name: 'office', sort: '', filtering: {filterString: '', placeholder: 'Filter by Location'}},
    {title: 'Date', className: 'text-warning', name: 'startDate'},
  
  ];
  public page:number = 1;
  public itemsPerPage:number = 10;
  public maxSize:number = 5;
  public numPages:number = 1;
  public length:number = 0;

  public config:any = {
    paging: true,
    sorting: {columns: this.columns},
    filtering: {filterString: ''},
    className: ['table-striped', 'table-bordered']
  };

  private data:Array<any> = [];

 constructor(private http: Http) {this.length = this.data.length;}

/*
* When the component is loaded, we want to fill this.data array with
*  the JSON data we are retrieving with the HTTP GET request.
*/
public ngOnInit(){
     this.getJsonData().subscribe(itemsFromGetRequest =>{
         /* Loop through the items for the HTTP GET request and insert them into the data array (the table). */
         itemsFromGetRequest.forEach(item => {
             this.data.push(item);
             this.length = this.data.length; // this is for pagination
    this.onChangeTable(this.config);

         });
     });
}

public getJsonData(): Observable<any[]>{
  /* Change this to the URL of the API you are requesting the data from. */
  let uri = 'https://....your.rest..../table-data.json';
  return this.http.get(uri)
        .map((response: Response) => {
            let items = response.json(); /* Here is where the table is filled with data. */
            return items;
    }).catch((error:any) => Observable.throw(error.json().error || 'Error retrieving the data.'));
}



  public changePage(page:any, data:Array<any> = this.data):Array<any> {
    let start = (page.page - 1) * page.itemsPerPage;
    let end = page.itemsPerPage > -1 ? (start + page.itemsPerPage) : data.length;
    return data.slice(start, end);
  }

  public changeSort(data:any, config:any):any {
    if (!config.sorting) {
      return data;
    }

    let columns = this.config.sorting.columns || [];
    let columnName:string = void 0;
    let sort:string = void 0;

    for (let i = 0; i < columns.length; i++) {
      if (columns[i].sort !== '' && columns[i].sort !== false) {
        columnName = columns[i].name;
        sort = columns[i].sort;
      }
    }

    if (!columnName) {
      return data;
    }

    // simple sorting
    return data.sort((previous:any, current:any) => {
      if (previous[columnName] > current[columnName]) {
        return sort === 'desc' ? -1 : 1;
      } else if (previous[columnName] < current[columnName]) {
        return sort === 'asc' ? -1 : 1;
      }
      return 0;
    });
  }

  public changeFilter(data:any, config:any):any {
    let filteredData:Array<any> = data;
    this.columns.forEach((column:any) => {
      if (column.filtering) {
        filteredData = filteredData.filter((item:any) => {
          return item[column.name].match(column.filtering.filterString);
        });
      }
    });

    if (!config.filtering) {
      return filteredData;
    }

    if (config.filtering.columnName) {
      return filteredData.filter((item:any) =>
        item[config.filtering.columnName].match(this.config.filtering.filterString));
    }

    let tempArray:Array<any> = [];
    filteredData.forEach((item:any) => {
      let flag = false;
      this.columns.forEach((column:any) => {
        if (item[column.name].toString().match(this.config.filtering.filterString)) {
          flag = true;
        }
      });
      if (flag) {
        tempArray.push(item);
      }
    });
    filteredData = tempArray;

    return filteredData;
  }

  public onChangeTable(config:any, page:any = {page: this.page, itemsPerPage: this.itemsPerPage}):any {
    if (config.filtering) {
      Object.assign(this.config.filtering, config.filtering);
    }

    if (config.sorting) {
      Object.assign(this.config.sorting, config.sorting);
    }

    let filteredData = this.changeFilter(this.data, this.config);
    let sortedData = this.changeSort(filteredData, this.config);
    this.rows = page && config.paging ? this.changePage(page, sortedData) : sortedData;
    this.length = sortedData.length;
  }

  public onCellClick(data: any): any {
    console.log(data);
  }
}
