### ISSUE TITLE
Can't bind to 'totalItems' since it isn't a known property of 'pagination'.

### ISSUE THREAD

**Issue by jhonattan471** [valor-software/ng2-table#446]
I followed the steps:

1. npm i ng2-table --save

******console log**************************************************************************************
+-- UNMET PEER DEPENDENCY @angular/common@2.4.5
+-- UNMET PEER DEPENDENCY @angular/compiler@2.4.5
+-- UNMET PEER DEPENDENCY @angular/core@2.4.5
+-- UNMET PEER DEPENDENCY @angular/forms@2.4.5
`-- ng2-table@1.3.2

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN ng2-table@1.3.2 requires a peer of @angular/common@~2.0.0 but none was installed.
npm WARN ng2-table@1.3.2 requires a peer of @angular/compiler@~2.0.0 but none was installed.
npm WARN ng2-table@1.3.2 requires a peer of @angular/core@~2.0.0 but none was installed.
npm WARN ng2-table@1.3.2 requires a peer of @angular/forms@~2.0.0 but none was installed.

*************************************************************************************************************

2.  import { Ng2TableModule } from 'ng2-table/ng2-table'; in app.module.ts and add to imports array

3. copy to my project:

ng2-table/demo/components/table/table-data.ts
ng2-table/demo/components/table/table-demo.html
ng2-table/demo/components/table/table-demo.ts

4. try to run

************console.log**************************
Unhandled Promise rejection: Template parse errors:
Can't bind to 'totalItems' since it isn't a known property of 'pagination'
Can't bind to 'itemsPerPage' since it isn't a known property of 'pagination'
...
**************************************************

**Comment by jhonattan471** [comment]
also import { Ng2TableModule } from 'ng2-table/ng2-table';  in  app.module.ts and add to imports array

**Comment by mikey923** [comment]
You have to install valor's ng2-bootstrap for the pagination component:
https://valor-software.com/ng2-bootstrap/#/

Edit:  You also get weird errors when the data your giving to the table isn't what was expected.  Try manually setting the data like 
`this.data = [
  {
    "id": 1,
    "name": "Leanne Graham",
    "username": "Bret",
    "email": "Sincere@april.biz",
    "address": {
      "street": "Kulas Light",
      "suite": "Apt. 556",
      "city": "Gwenborough",
      "zipcode": "92998-3874",
      "geo": {
        "lat": "-37.3159",
        "lng": "81.1496"
      }
    },
    "phone": "1-770-736-8031 x56442",
    "website": "hildegard.org",
    "company": {
      "name": "Romaguera-Crona",
      "catchPhrase": "Multi-layered client-server neural-net",
      "bs": "harness real-time e-markets"
    }
  },
  {
    "id": 2,
    "name": "Ervin Howell",
    "username": "Antonette",
    "email": "Shanna@melissa.tv",
    "address": {
      "street": "Victor Plains",
      "suite": "Suite 879",
      "city": "Wisokyburgh",
      "zipcode": "90566-7771",
      "geo": {
        "lat": "-43.9509",
        "lng": "-34.4618"
      }
    },
    "phone": "010-692-6593 x09125",
    "website": "anastasia.net",
    "company": {
      "name": "Deckow-Crist",
      "catchPhrase": "Proactive didactic contingency",
      "bs": "synergize scalable supply-chains"
    }
  }];`

Data courtesy of http://jsonplaceholder.typicode.com/

**Comment by jhonattan471** [comment]
Thanks for the reply but the problem remains the same...

I followed the steps:

1. npm install ng2-bootstrap --save
2. edit data, now is : 
 private data:Array<any> =  [ { "id": 1, "name": "Leanne Graham", "username": "Bret", "email": "Sincere@april.biz", "address": { "street": "Kulas Light", "suite": "Apt. 556", "city": "Gwenborough", "zipcode": "92998-3874", "geo": { "lat": "-37.3159", "lng": "81.1496" } }, "phone": "1-770-736-8031 x56442", "website": "hildegard.org", "company": { "name": "Romaguera-Crona", "catchPhrase": "Multi-layered client-server neural-net", "bs": "harness real-time e-markets" } }, { "id": 2, "name": "Ervin Howell", "username": "Antonette", "email": "Shanna@melissa.tv", "address": { "street": "Victor Plains", "suite": "Suite 879", "city": "Wisokyburgh", "zipcode": "90566-7771", "geo": { "lat": "-43.9509", "lng": "-34.4618" } }, "phone": "010-692-6593 x09125", "website": "anastasia.net", "company": { "name": "Deckow-Crist", "catchPhrase": "Proactive didactic contingency", "bs": "synergize scalable supply-chains" } }];

**Comment by jhonattan471** [comment]
Ok, this solve my problem : 

I followed the steps:

1. INSTALL 
npm i ng2-table --save
npm install ng2-bootstrap --save

2. IMPORT
import { Ng2TableModule } from 'ng2-table/ng2-table'; 
import { PaginationModule } from 'ng2-bootstrap/ng2-bootstrap'; array
import { TabsModule } from 'ng2-bootstrap/ng2-bootstrap'; 
and add this elements to imports array

**Comment by soofy** [comment]
when i  run  install ng2-bootstrap --save  the scripts  uninstalls  ng2-table.. what can we do ?

**Comment by webrexRavi** [comment]
Solution for me is as below:

INSTALL
npm install ng2-bootstrap --save

IMPORT
import { PaginationModule } from 'ng2-bootstrap/pagination';

DECLARE

  imports: [
      PaginationModule.forRoot(),
  ],

**Comment by sabbane** [comment]
Why is it necessary to import PaginationModule.forRoot() instead of PaginationModule ?

**Comment by webrexRavi** [comment]
[May be this can help you](https://stackoverflow.com/questions/39664861/importing-modules-with-forroot)
