### ISSUE TITLE
How to add button(edit or delete) in <ng-table>

### ISSUE THREAD

**Issue by qwe852147** [valor-software/ng2-table#450]
I use following code to add button in each row but it doesn't binding function .

` row[column.name]="<input type='"+InputType+"' (click)='"+Input.click+"'  value='"+Input.input.value+"'></input>"; `

In HTML it is <input type='button ' (click)='Input click function()'  value='button value'></input> but the function can not work.

Any solution to bind function to button?

**Comment by abdulkareemgs** [comment]
You can do it by passing your rows as 

`rows = [ {'delete'='<i class="fa fa-trash" aria-hidden="true"></i>'},...`
handle click in `cellClicked` event handler with filter  `event.column === 'delete'`

but there is a catch icons are unresponsive to click event see #448

**Comment by qwe852147** [comment]
Thanks!
But I have another problem how add check box to the row?
I use  <input type='checkbox' /> into row but it can be checked.
