### ISSUE TITLE
Filter issue when changing page

### ISSUE THREAD

**Issue by mcannon2** [valor-software/ng2-table#488]
Filter on all columns and change the page. If you then filter on a different value occurring in a row that wasn't shown in the prior search, it will not appear. If you then clear that filter, nothing shows.

**Comment by mcannon2** [comment]
Seems to happen while using multiple columns too. Shouldn't everything reset if all of the filter inputs are cleared?

**Comment by webcat12345** [comment]
Focus on ChangeDetectorRef while filtering columns and pagination. Check console if there is no error.

**Comment by webcat12345** [comment]
https://github.com/valor-software/ng2-table/issues/397

**Comment by mcannon2** [comment]
Thanks! Sorry, I didn't see that.
