### ISSUE TITLE
Get Index of row

### ISSUE THREAD

**Issue by TeodorKolev** [valor-software/ng2-table#540]
Is it possible to get index of row? I am using:
```
 <tr *ngFor="let row of rows; let i = index">
    <td *ngIf="tableName == 'somename'">{{ i + 1 }}</td>
    <td (click)="cellClick(row, column.name)" *ngFor="let column of columns" [innerHtml]="sanitize(getData(row, column.name))"></td>
  </tr>
```
but when I use pagination it starts from 1 in every page.

**Comment by qwe852147** [comment]
try  to change  {{ i + 1 }} to {{ currentPagenum * itemsPerPage+i+1}}?

**Comment by TeodorKolev** [comment]
I have solved it [that](http://stackoverflow.com/questions/44045936/angular-2-get-dynamic-value-between-components/44046054#44046054) way
