### ISSUE TITLE
Can we apply class to row? For example:  show particular row in red color

### ISSUE THREAD

**Issue by priyakokas** [valor-software/ng2-table#543]

**Comment by Sam2243** [comment]
Hi,

How did you do that? I actually cannot iterate over rows in my html.That's what i m trying to do but not working..

<```
ng-table [config]="config"
          [columns]="columns">
          	<tr *ngFor="let row of rows">
          		<td>1</td>
          		<td>{{ row.eid }}</td>
          		<td>{{ row.rankValue }}</td>
          		<td>{{ row.reason.similarilty }}</td>
          	</tr>
        </ng-table> 
```
