### ISSUE TITLE
Colors not changing when className is added to code

### ISSUE THREAD

**Issue by jessicalam** [valor-software/ng2-table#566]
When the className is added to the code, I should be able to put in the class name into the stlyesheet and things should be able to change right? Like the color of the background?
`	{title: 'Due Date', name: 'dueDate', sort: 'asc', className:'dueDateColor'}`
-
`
.dueDateColor::before{
	background-color: rgb(255, 134, 134);
}
.dueDateColor {
	background-color:rgb(253, 255, 142);
}
.dueDateColor::after {
	background-color: rgb(108, 255, 127);

}`

**Comment by themese** [comment]
I am using a custom css class that makes the cursor a hand and it works fine. 

Can you provide a plnkr or something similar?
Mese

**Comment by jessicalam** [comment]
So what I've written isn't wrong then?

Also, thanks for letting me know. 
It could be other people's code that is making it not look a certain way.

**Comment by themese** [comment]
Try putting !important in your css code to check if it's other's people code or yours.

If with !important on your css it works it means it's not the pluging.
If it doesn't work even with it, it might something else. 
```
dueDateColor::before{
background-color: rgb(255, 134, 134) !important;
}
.dueDateColor {
background-color:rgb(253, 255, 142) !important;
}
.dueDateColor::after {
background-color: rgb(108, 255, 127 !important);

}
```
Please let us know even it it works, so others can use this issue :)

Mese

**Comment by jessicalam** [comment]
this doesn't work with it. so it might be something else. thank you anyways. :)

**Comment by samuelkavin** [comment]
You can try like this:
`table.table.dataTable thead th.dueDateColor::before{background-color: rgb(255, 134, 134);}`
