### ISSUE TITLE
Filter will crash when type some special symbols

### ISSUE THREAD

**Issue by qwe852147** [valor-software/ng2-table#582]
Filter will crash when type some special symbols.
example  "\" or "*" etc..

**Comment by Gamboster** [comment]
Same issue here. Any solution for this ?

Here an screen of the error
![angular2_table](https://user-images.githubusercontent.com/10983458/31964433-5b1e9952-b8da-11e7-98ba-9b64de8110e9.png)

**Comment by qwe852147** [comment]
Change .match to .includes in changeFilter function will be fine

**Comment by Gamboster** [comment]
It works fine with ".includes" . Thank you!
